---
title: "Figure4"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Figure4}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, include = FALSE}
devtools::load_all(".", quiet = TRUE)
library(EIFAnalysis)
```

```{r figure4_part1}
  plot.km.EIF.all.tumors("EIF4G1")
```

```{r figure4_part2}
  lapply(
    c(
      "EIF4E", "EIF4E2", "EIF4E3",
      "EIF4G1", "EIF4G2", "EIF4G3",
      "EIF4A1", "EIF4A2",
      "EIF4EBP1", "PABPC1", "MKNK1", "MKNK2",
      "DDX3X", "EIF4B", "EIF4H", "EIF2S1",
      "EIF3A", "EIF3B", "EIF3C", "EIF3D",
      "EIF3E", "EIF3F", "EIF3G", "EIF3H",
      "EIF3I", "EIF3J", "EIF3K", "EIF3L", "EIF3M",
      "EIF4B", "EIF4H",
      "MTOR", "RPTOR", "RICTOR", "RPS6KB1", "MYC"
    ), plot.km.EIF.all.tumors
  )
```

```{r figure4_part3}
  plot.km.EIF.each.tumor(
    EIF = "EIF4G1",
    tumor = c("lung adenocarcinoma")
  )
```

```{r figure4_part4}
  lapply(
    c(
      "EIF4E", "EIF4G1", "EIF4G2", "EIF4A1",
      "EIF4EBP1", "PABPC1", "MKNK1", "MKNK2",
      "MTOR", "RPTOR", "RPS6KB1", "MYC"
    ),
    plot.km.EIF.each.tumor,
    tumor = "lung adenocarcinoma"
  )
```

```{r figure4_part5}
  plot.coxph.EIF.all.tumors()
```

```{r figure4_part6}
  plot.coxph.EIF.each.tumor(c("lung adenocarcinoma"))
```
